package dev.atvremote.protocol.session

import dev.atvremote.protocol.connection.CommandChannel

/**
 * Post-verify session handshake for the Apple TV Companion protocol.
 *
 * Ports `CompanionAPI.connect` from pyatv's `api.py`, executing the four
 * request/response exchanges and one outbound event that establish a session
 * after HAP pair-verify completes:
 *
 *  1. `_systemInfo`   — device capabilities advertisement
 *  2. `_touchStart`   — touch-surface registration
 *  3. `_sessionStart` — combined session-ID negotiation: (remoteSid shl 32) or localSid
 *  4. `_tiStart`      — touch-interface init
 *  5. `_interest`     — subscribe to media-control events (`_iMC`)
 *
 * The combined [sid] is `(remoteSid shl 32) or localSid`, where `remoteSid`
 * is read from the Apple TV's `_sessionStart` response
 * (`resp["_c"]["_sid"]` as [Long]) and `localSid` is generated by [sidGenerator]
 * (defaults to a 32-bit-range random long from [kotlin.random.Random]).
 *
 * > NOTE: The exact `_systemInfo` field values (e.g. `_bf`, `_cf`, `_clFl`,
 * > `_sf`, `_sv`, `_i`) are ported from pyatv and have not been validated
 * > against a real Apple TV device. Authoritative validation is deferred to
 * > **Task 17** (CLI smoke test with a real device).
 *
 * @param proto      abstraction over the Companion protocol's exchange/event surface.
 * @param deviceId   the Android device's public identifier (sent as `_pubID`).
 * @param clientId   the HAP client/pairing identifier (sent as `_idsID`; also
 *                   used as `_i` placeholder — Task 17 may replace with a real rpId).
 * @param name       human-readable device name (e.g. "Pixel").
 * @param model      device model string (e.g. "Pixel 8").
 * @param sidGenerator  factory for the local 32-bit session-id component; injected
 *                      for deterministic testing. Defaults to [kotlin.random.Random]
 *                      in the [0, 2^32) range.
 */
class SessionHandshake(
    private val proto: CommandChannel,
    private val deviceId: String,
    private val clientId: String,
    private val name: String,
    private val model: String,
    private val sidGenerator: () -> Long = { kotlin.random.Random.nextLong(0, 1L shl 32) },
) {
    /** Combined session ID after [run] completes: `(remoteSid shl 32) or localSid`. */
    var sid: Long = 0L
        private set

    private var ran = false

    /**
     * Executes the five-step handshake in order.
     * Must be called exactly once after HAP pair-verify succeeds.
     *
     * @throws IllegalStateException if the Apple TV's `_sessionStart` response
     *   does not contain a `_sid` field inside `_c`.
     */
    suspend fun run() {
        check(!ran) { "SessionHandshake.run() must be called exactly once" }
        ran = true
        // 1. Advertise system capabilities.
        // Field values ported from pyatv CompanionAPI.connect; pending real-device
        // validation in Task 17. `_i` uses clientId as a deterministic placeholder
        // (the actual rpId field on real devices may differ).
        proto.exchange(
            "_systemInfo",
            mapOf(
                "_bf" to 0,
                "_cf" to 512,
                "_clFl" to 128,
                "_i" to clientId,
                "_idsID" to clientId,
                "_pubID" to deviceId,
                "_sf" to 256,
                "_sv" to "170.18",
                "model" to model,
                "name" to name,
            ),
        )

        // 2. Register a 1000×1000 virtual touch surface.
        proto.exchange(
            "_touchStart",
            mapOf(
                "_height" to 1000.0,
                "_tFl" to 0,
                "_width" to 1000.0,
            ),
        )

        // 3. Negotiate a combined session ID.
        val localSid = sidGenerator()
        val sessionStartResp = proto.exchange(
            "_sessionStart",
            mapOf(
                "_srvT" to "com.apple.tvremoteservices",
                "_sid" to localSid,
            ),
        )
        @Suppress("UNCHECKED_CAST")
        val contentMap = sessionStartResp["_c"] as? Map<*, *>
            ?: error("SessionHandshake: _sessionStart response missing '_c' map")
        val remoteSid = (contentMap["_sid"] as? Number)?.toLong()
            ?: error("SessionHandshake: _sessionStart response '_c._sid' is absent or not a Long " +
                     "(got ${contentMap["_sid"]?.let { "${it::class.simpleName}($it)" } ?: "null"})")
        sid = (remoteSid shl 32) or localSid

        // 4. Initialise the touch interface.
        proto.exchange("_tiStart", emptyMap())

        // 5. Subscribe to media-control events (one-way; no response expected).
        proto.sendEvent("_interest", mapOf("_regEvents" to listOf("_iMC")))
    }
}
